apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp-nginx
    namespace: nsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-nginx
  template:
    metadata:
      labels:
        app: myapp-nginx
    spec:
      containers:
      - name: myapp-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080




