apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ .Values.appName}}'
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Rupagowthaman/Test-Argocd.git
        revision: main
        directories:
          - path: dev

  template:
    metadata:
      name: '{{ .Values.appName}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/Rupagowthaman/Test-Argocd.git
        targetRevision: main
        path: dev

      destination:
        server: https://kubernetes.default.svc
        namespace: '{.Values.appName}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true