apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-ApplicationSet
  namespace: argocd
spec:
  generators:
    -list:
      elements:
      - name: App1
        path: dev/charts/App1
        namespace: app1
      - name: App2
        path: dev/charts/App2
        namespace: App2
    
  template:
    metadata:
      name: '{{ .Values.appName}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/Rupagowthaman/Test-Argocd.git
        targetRevision: HEAD
        path: dev
      destination:
        server: https://kubernetes.default.svc
        namespace: '{namespace}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true