apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ .Values.appName}}'
  namespace: argocd
spec:
  generators:
    -list:
      elements:
      - name: app1
        path: charts/app1
        namespace: app1
      - name: app2
        path: charts/app2
        namespace: app2
    
  template:
    metadata:
      name: '{{ .Values.appName}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/Rupagowthaman/Test-Argocd.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{namespace}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true